plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mintechstrategy.kimgosu'
    compileSdk 37

    defaultConfig {
        applicationId 'com.mintechstrategy.kimgosu'
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName '0.2.0-test'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
